### ISSUE TITLE
API Gateway部分のserverless framework適用(/createChannelで実行できるように)

### ISSUE THREAD

**Issue by matchasong** [matchasong/createSlackChannel#9]
API Gateway部分のserverless framework適用(/createChannelで実行できるように)

**Comment by matchasong** [comment]
serverless.ymlのfunction.mainにhttpを追加したところ、リクエストを受け付けるようになった。
ただし、内部エラーが返って来てしまう

serverless.yml
```
functions:
  main:
    handler: src/main.handler
    timeout: 180
    events:
    (略)
      - http:
          path: createAndArchive
          method: post
```

**Comment by matchasong** [comment]
```
$ curl -X POST https://XXXXXXXXXXXXXXXX/createAndArchive
{"message": "Internal server error"}
```

**Comment by matchasong** [comment]
main.pyにレスポンスを返す処理を追加

```
       body = {
            "message": 'Processing completed successfully.',
            "input": event
        }
        response = {
            "statusCode": 200,
            "body": json.dumps(body)
        }
```

**Comment by matchasong** [comment]
処理はできていて、CloudWatchには正常終了のログも出ているが、
スラッシュコマンドの戻りはtimeoutが返ってくる。

```
/createchannel failed with the error "operation_timeout"
```

**Comment by matchasong** [comment]
APIGateway側のタイムアウトの設定を見直す

**Comment by matchasong** [comment]
APIGateway側ではなく、slack側のタイムアウト(3000ms)だった。
https://api.slack.com/interactivity/slash-commands

**Comment by matchasong** [comment]
slack側のタイムアウトを変更することはできないらしいので、
lambdaを非同期呼び出しすることで、タイムアウト前にレスポンスが返せるようにした。
事象の解消を確認。

```
      - http:
          path: createAndArchive
          method: post
          async: true
```
